version: '3.8'

services:

  jwtdemo:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

  mongo:
    image: mongo:7.0.2-jammy
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jose
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/vscode/data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://jose:password@mongo:27017/
